# https://taskfile.dev

version: '3'

tasks:

  init:
    desc: Initialize cockroachdb extensions and operators
    cmds:
      - kubectl apply -f conf/crdbclusters.yaml
      - kubectl apply -f conf/operator.yaml

  deploy:
    desc: Deploy a cockroachdb cluster
    cmds:
      - kubectl apply -f ./conf/deployment.yaml

  clean:
    desc: Teardown database
    cmds:
      - kubectl delete -f ./conf/deployment.yaml

  sql:
    desc: Open a database shell
    vars:
      DB_INDEX: 0
    cmds:
      - kubectl exec ledger-db-{{.DB_INDEX}}
        --stdin
        --tty
        -- cockroach sql --certs-dir cockroach-certs
