# https://taskfile.dev

version: '3'

tasks:

  deploy:
    desc: Deploy an empty database
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm install ledgerdb --version 10.2.6 bitnami/postgresql
    status:
      - helm repo list | grep bitnami
      - ! helm status ledgerdb

  destroy:
    desc: Undeploy a database
    cmds:
      - helm delete ledgerdb
      - kubectl delete pvc -l release=ledgerdb

  export:
    cmds:
      - export POSTGRES_PASSWORD=$(kubectl get secret --namespace default ledgerdb-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
    status:
      - test -n "$POSTGRES_PASSWORD"

  shell:
    deps: [export]
    cmds:
      - kubectl run ledgerdb-postgresql-client
        --rm
        --tty
        --stdin
        --restart='Never'
        --namespace default
        --image docker.io/bitnami/postgresql:11.10.0-debian-10-r60
        --env="PGPASSWORD=$POSTGRES_PASSWORD"
        --command
        -- psql
        --host ledgerdb-postgresql -U postgres -d postgres -p 5432
